// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AppAsideSticky: typeof import('./src/components/AppAsideSticky.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSideBar: typeof import('./src/components/AppSideBar.vue')['default']
    AppSideSticky: typeof import('./src/components/AppSideSticky.vue')['default']
    AppTopNav: typeof import('./src/components/AppTopNav.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
