// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSideBar: typeof import('./src/components/AppSideBar.vue')['default']
    AppTopNav: typeof import('./src/components/AppTopNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewArticle: typeof import('./src/components/NewArticle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
